version: '3'

services:
  chain_midware:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'yqr/midware'
    ports:
      - "80:80"
    links:
      - chaindb

  chaindb:
    image: 'mongo'
    ports:
      - "27017:27017"

  btc_wallet:
    build:
      context: .
      dockerfile: Dockerfile.btc_wallet
    image: yqr/btc_wallet
